services:
  donut-pipeline:
    build: .
    container_name: donut-pipeline
    ports:
      - "7860:7860"
    env_file:
      - stack.env
    volumes:
      - /net/models:/root/.cache/huggingface
      - donut-data:/data
    restart: unless-stopped

volumes:
  donut-data:
